/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.playground.kotlin.coroutines

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    println("Runnint in thread ${Thread.currentThread().name}")
}
